[package]
name = "spotify-core"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11"
flacenc = { version = "0.5.1", default-features = false, features = ["log"] }
librespot = "=0.8.0"
rustfft = "=6.4.1"
rodio = { version = "=0.21.1", default-features = false, features = ["playback", "claxon", "wav", "mp3"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swift-bridge = { version = "=0.1.59", features = ["async"] }
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }

[build-dependencies]
swift-bridge-build = "=0.1.59"

[lib]
crate-type = ["staticlib"]

[patch.crates-io]
librespot-core = { path = "vendor/librespot-core" }
